### ISSUE TITLE
All VTock Fixpoint Encoding issues

### ISSUE THREAD

**Issue by vrindisbacher** [flux-rs/flux#1036]
AFAIKCT, these are the two that are currently crashing:

[`allocate_app_memory_regions`](https://github.com/PLSysSec/tock/blob/926530db7f9328c1dd2f04b20e04a5e256718318/arch/cortex-m/src/mpu.rs#L1065)

```rust
error: internal compiler error: crates/flux-infer/src/fixpoint_encoding.rs:485:43: fixpoint crash: CrashInfo([Array [Array [Array [Number(-1), Null], String("elaborate solver failed on:\n    not (tuple7$3 (arr_select_m reftgen$old_c$6 0))\n    || ((0 < tuple7$4 (arr_select_m reftgen$old_c$6 0)\n         && 0 + 4294967295 <= tuple7$4 (arr_select_m reftgen$old_c$6 0))\n        || 0 >= tuple7$4 (arr_select_m reftgen$old_c$6 0) + tuple7$5 (arr_select_m reftgen$old_c$6 0))\nwith error\n    The sort (Array_t @(227) @(1)) is not numeric\n  because\nCannot unify (Array_t @(227) @(1)) with int in expression: arr_select_m reftgen$old_c$6 \nin environment\n    arr_select_m := func(1 , [(Array_t @(0) @(1)); @(0); @(1)])\n\n    reftgen$old_c$6 := int\n\n    tuple7$3 := func(7 , [(Tuple7 @(0) @(1) @(2) @(3) @(4) @(5) @(6));\n                          @(3)])\n\n    tuple7$4 := func(7 , [(Tuple7 @(0) @(1) @(2) @(3) @(4) @(5) @(6));\n                          @(4)])\n\n    tuple7$5 := func(7 , [(Tuple7 @(0) @(1) @(2) @(3) @(4) @(5) @(6));\n                          @(5)])")]], String(":1:1-1:1: Error\n  elaborate solver failed on:\n      not (tuple7$3 (arr_select_m reftgen$old_c$6 0))\n      || ((0 < tuple7$4 (arr_select_m reftgen$old_c$6 0)\n           && 0 + 4294967295 <= tuple7$4 (arr_select_m reftgen$old_c$6 0))\n          || 0 >= tuple7$4 (arr_select_m reftgen$old_c$6 0) + tuple7$5 (arr_select_m reftgen$old_c$6 0))\n  with error\n      The sort (Array_t @(227) @(1)) is not numeric\n  because\nCannot unify (Array_t @(227) @(1)) with int in expression: arr_select_m reftgen$old_c$6 \n  in environment\n      arr_select_m := func(1 , [(Array_t @(0) @(1)); @(0); @(1)])\n\n      reftgen$old_c$6 := int\n\n      tuple7$3 := func(7 , [(Tuple7 @(0) @(1) @(2) @(3) @(4) @(5) @(6));\n                            @(3)])\n\n      tuple7$4 := func(7 , [(Tuple7 @(0) @(1) @(2) @(3) @(4) @(5) @(6));\n                            @(4)])\n\n      tuple7$5 := func(7 , [(Tuple7 @(0) @(1) @(2) @(3) @(4) @(5) @(6));\n                            @(5)])")])
``` 

[`update_app_memory_regions`](https://github.com/PLSysSec/tock/blob/926530db7f9328c1dd2f04b20e04a5e256718318/arch/cortex-m/src/mpu.rs#L1239):

```rust
error: internal compiler error: crates/flux-infer/src/fixpoint_encoding.rs:485:43: fixpoint crash: CrashInfo([Array [Array [Array [Number(-1), Null], String("elaborate solver failed on:\n    tuple7$3 (arr_select_m reftgen$old_c$5 2)\nwith error\n    The sort (Array_t @(95) @(1)) is not numeric\n  because\nCannot unify (Array_t @(95) @(1)) with int in expression: arr_select_m reftgen$old_c$5 \nin environment\n    arr_select_m := func(1 , [(Array_t @(0) @(1)); @(0); @(1)])\n\n    reftgen$old_c$5 := int\n\n    tuple7$3 := func(7 , [(Tuple7 @(0) @(1) @(2) @(3) @(4) @(5) @(6));\n                          @(3)])")]], String(":1:1-1:1: Error\n  elaborate solver failed on:\n      tuple7$3 (arr_select_m reftgen$old_c$5 2)\n  with error\n      The sort (Array_t @(95) @(1)) is not numeric\n  because\nCannot unify (Array_t @(95) @(1)) with int in expression: arr_select_m reftgen$old_c$5 \n  in environment\n      arr_select_m := func(1 , [(Array_t @(0) @(1)); @(0); @(1)])\n\n      reftgen$old_c$5 := int\n\n      tuple7$3 := func(7 , [(Tuple7 @(0) @(1) @(2) @(3) @(4) @(5) @(6));\n                            @(3)])")])
```

[`configure_mpu`](https://github.com/PLSysSec/tock/blob/9d630ab91e44832dd4c340940eee469cc6e73a59/arch/cortex-m/src/mpu.rs#L1325):

```rust
error: internal compiler error: crates/flux-infer/src/fixpoint_encoding.rs:485:43: fixpoint crash: CrashInfo([Array [Array [Array [Number(-1), Null], String("Constraint with free vars\n1\n[constgen$MIN_REGION_SIZE$0]\nTry using the --prune-unsorted flag")], Array [Array [Number(-1), Null], String("Constraint with free vars\n2\n[constgen$MIN_REGION_SIZE$0]\nTry using the --prune-unsorted flag")], Array [Array [Number(-1), Null], String("Constraint with free vars\n3\n[constgen$MIN_REGION_SIZE$0]\nTry using the --prune-unsorted flag")], Array [Array [Number(-1), Null], String("Constraint with free vars\n4\n[constgen$MIN_REGION_SIZE$0]\nTry using the --prune-unsorted flag")], Array [Array [Number(-1), Null], String("Constraint with free vars\n5\n[constgen$MIN_REGION_SIZE$0]\nTry using the --prune-unsorted flag")], Array [Array [Number(-1), Null], String("Constraint with free vars\n6\n[constgen$MIN_REGION_SIZE$0]\nTry using the --prune-unsorted flag")], Array [Array [Number(-1), Null], String("Constraint with free vars\n7\n[constgen$MIN_REGION_SIZE$0]\nTry using the --prune-unsorted flag")], Array [Array [Number(-1), Null], String("Constraint with free vars\n8\n[constgen$MIN_REGION_SIZE$0]\nTry using the --prune-unsorted flag")], Array [Array [Number(-1), Null], String("Constraint with free vars\n9\n[constgen$MIN_REGION_SIZE$0]\nTry using the --prune-unsorted flag")], Array [Array [Number(-1), Null], String("Constraint with free vars\n10\n[constgen$MIN_REGION_SIZE$0]\nTry using the --prune-unsorted flag")], Array [Array [Number(-1), Null], String("Constraint with free vars\n11\n[constgen$MIN_REGION_SIZE$0]\nTry using the --prune-unsorted flag")], Array [Array [Number(-1), Null], String("Constraint with free vars\n12\n[constgen$MIN_REGION_SIZE$0]\nTry using the --prune-unsorted flag")], Array [Array [Number(-1), Null], String("Constraint with free vars\n13\n[constgen$MIN_REGION_SIZE$0]\nTry using the --prune-unsorted flag")], Array [Array [Number(-1), Null], String("Constraint with free vars\n14\n[constgen$MIN_REGION_SIZE$0]\nTry using the --prune-unsorted flag")], Array [Array [Number(-1), Null], String("Constraint with free vars\n15\n[constgen$MIN_REGION_SIZE$0]\nTry using the --prune-unsorted flag")], Array [Array [Number(-1), Null], String("Constraint with free vars\n16\n[constgen$MIN_REGION_SIZE$0]\nTry using the --prune-unsorted flag")]], String(":1:1-1:1: Error\n  Constraint with free vars\n  1\n  [constgen$MIN_REGION_SIZE$0]\n  Try using the --prune-unsorted flag\n:1:1-1:1: Error\n  Constraint with free vars\n  2\n  [constgen$MIN_REGION_SIZE$0]\n  Try using the --prune-unsorted flag\n:1:1-1:1: Error\n  Constraint with free vars\n  3\n  [constgen$MIN_REGION_SIZE$0]\n  Try using the --prune-unsorted flag\n:1:1-1:1: Error\n  Constraint with free vars\n  4\n  [constgen$MIN_REGION_SIZE$0]\n  Try using the --prune-unsorted flag\n:1:1-1:1: Error\n  Constraint with free vars\n  5\n  [constgen$MIN_REGION_SIZE$0]\n  Try using the --prune-unsorted flag\n:1:1-1:1: Error\n  Constraint with free vars\n  6\n  [constgen$MIN_REGION_SIZE$0]\n  Try using the --prune-unsorted flag\n:1:1-1:1: Error\n  Constraint with free vars\n  7\n  [constgen$MIN_REGION_SIZE$0]\n  Try using the --prune-unsorted flag\n:1:1-1:1: Error\n  Constraint with free vars\n  8\n  [constgen$MIN_REGION_SIZE$0]\n  Try using the --prune-unsorted flag\n:1:1-1:1: Error\n  Constraint with free vars\n  9\n  [constgen$MIN_REGION_SIZE$0]\n  Try using the --prune-unsorted flag\n:1:1-1:1: Error\n  Constraint with free vars\n  10\n  [constgen$MIN_REGION_SIZE$0]\n  Try using the --prune-unsorted flag\n:1:1-1:1: Error\n  Constraint with free vars\n  11\n  [constgen$MIN_REGION_SIZE$0]\n  Try using the --prune-unsorted flag\n:1:1-1:1: Error\n  Constraint with free vars\n  12\n  [constgen$MIN_REGION_SIZE$0]\n  Try using the --prune-unsorted flag\n:1:1-1:1: Error\n  Constraint with free vars\n  13\n  [constgen$MIN_REGION_SIZE$0]\n  Try using the --prune-unsorted flag\n:1:1-1:1: Error\n  Constraint with free vars\n  14\n  [constgen$MIN_REGION_SIZE$0]\n  Try using the --prune-unsorted flag\n:1:1-1:1: Error\n  Constraint with free vars\n  15\n  [constgen$MIN_REGION_SIZE$0]\n  Try using the --prune-unsorted flag\n:1:1-1:1: Error\n  Constraint with free vars\n  16\n  [constgen$MIN_REGION_SIZE$0]\n  Try using the --prune-unsorted flag")])
```

**Comment by nilehmann** [comment]
@vrindisbacher is https://github.com/flux-rs/flux/issues/1025#issuecomment-2734750314 a separate issue? If so, can you please update the OP with that and close the other issue?

**Comment by vrindisbacher** [comment]
Updated.

**Comment by nilehmann** [comment]
@vrindisbacher https://github.com/flux-rs/flux/pull/1043 should have fixed at least some of these, but I'm getting #1038 on all of them so I don't know if there's anything left to do.

```
error[E0999]: mismatched sorts
   --> kernel/src/process_standard.rs:371:61
    |
371 |         <<C as Chip>::MPU as MPU>::config_can_access_heap(bc.mpu_config, mem_start, bc.app_break) &&
    |                                                             ^^^^^^^^^^^ expected `<<C[b1] as Chip>::MPU[b0] as MPU>::MpuConfig::sort`, found `<<C[b1] as Chip>::MPU[b0] as MPU>::MpuConfig::sort`

```

I'm checking the commit in each link and then running `FLUX_CHECK_DEF=<function-in-the-link> cargo flux -p cortexm`

**Comment by vrindisbacher** [comment]
Let me see what happens on `master`.

**Comment by vrindisbacher** [comment]
I think this did fix the fixpoint encoding issues for `allocate` and `update`. I was able to remove `trusted_impl` for both. I'm still getting an error for `configure_mpu` though. Is that expected?

**Comment by nilehmann** [comment]
I don't know. I can't reproduce the error in `cofigure_mpu` because running on that commit gives me the mismatched sort error.

**Comment by nilehmann** [comment]
but yeah, that one seems to be a different issue

**Comment by nilehmann** [comment]
cool, I can reproduce now

**Comment by nilehmann** [comment]
@vrindisbacher, can you check if everything here is fixed after https://github.com/flux-rs/flux/pull/1044

**Comment by vrindisbacher** [comment]
@nilehmann everything is working!
